### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by psmukhopadhyay** [harvard-lil/warc-gpt#8]
I have just installed and tested with the test dataset on Chandrayaan-3 of ISRO by using mistral:latest model. It's working nice but I've observed that it is bit slow (my laptop spec is i7 12 core with 24 GB RAM with Ubuntu 22.04). For example, a question takes almost on an average 4 minutes to respond: 

[2024-04-02 **00:13:22**,123] WARNING in api: litellm could not trim messages for ollama/mistral:latest
127.0.0.1 - - [02/Apr/2024 **00:18:56**] "POST /api/completion HTTP/1.1" 200 -
127.0.0.1 - - [02/Apr/2024 **00:26:34**] "POST /api/completion HTTP/1.1" 200 -

Whereas when I use directly the ollama prompt, it is almost instantaneous (but of course it is not contextualized with the test datasets on the subject):

```
ollama run mistral
>>> What is Chandrayaan-3?
 Chandrayaan-3 is a proposed lunar mission by the Indian Space Research Organization (ISRO). It is the third lunar expedition by ISRO, following Chandrayaan-1 and Chandrayaan-2. The primary 
objective of Chandrayaan-3 is to soft land a rover on the Moon's South Polar Region to carry out scientific explorations and studies. The mission also includes a orbiter that will map the Moon in 
various wavelengths and study its resources and exosphere, as well as a lander. However, as of now, the launch has not been scheduled yet.
```
Any suggestion?

**Comment by matteocargnelutti** [comment]
Hi @psmukhopadhyay,

This is indeed very slow. 

A few things that come to mind that may help figure this out:
- Is the vector store large enough that ChromaDB runs out of RAM? This could be the case if you have ingested many WARCs, or very large WARCs.
- Are you using the default settings for the embedding model / vector store?

**Comment by psmukhopadhyay** [comment]
Thanks for your response.

1. Is the vector store large enough that ChromaDB runs out of RAM? This could be the case if you have ingested many WARCs, or very large WARCs.

There are altogether 7 WARC files totaling 5.9 MB only. The corresponding chromadb directory size is around 8.3 MB after ingest.
These WRAC files I've created on the basis of urls.txt as provided in the text dataset.

2. Are you using the default settings for the embedding model / vector store? Different text similarity models have different performance profiles.

If I understand your query here properly the WARC-GPT interface settings is like:

![image](https://github.com/harvard-lil/warc-gpt/assets/19376596/0a7ca6b8-0844-4d49-9330-c7a39715d452)

Regards

**Comment by matteocargnelutti** [comment]
@psmukhopadhyay 

1. Thanks for the info. It is very unlikely to be the issue then 😄 .
2. I was more referring to the settings in `.env` for everything related to `VECTOR_SEARCH_...`: it would be helpful to know if you changed any of these settings. 

> For example, a question takes almost on an average 4 minutes to respond
Do you have a sense what stage takes time (pulling results from the vector store vs. generating the response). 

I should note: there is a new version of WARC-GPT available that decouples search from completion.

**Comment by psmukhopadhyay** [comment]
@matteocargnelutti 

I find this section (VECTOR_SEARCH) in the .env file:

```
#-------------------------------------------------------------------------------
# Vector Store / Search settings
#-------------------------------------------------------------------------------
VECTOR_SEARCH_COLLECTION_NAME="collection"

VECTOR_SEARCH_SENTENCE_TRANSFORMER_MODEL="intfloat/e5-large-v2" # Can be any Sentence-Transformers compatible model available on Hugging Face
VECTOR_SEARCH_SENTENCE_TRANSFORMER_DEVICE="cpu"
VECTOR_SEARCH_DISTANCE_FUNCTION="cosine" # https://docs.trychroma.com/usage-guide#changing-the-distance-function
VECTOR_SEARCH_NORMALIZE_EMBEDDINGS="true"
VECTOR_SEARCH_CHUNK_PREFIX="passage: " # Can be used to add prefix to text embeddings stored in vector store
VECTOR_SEARCH_QUERY_PREFIX="query: " # Can be used to add prefix to text embeddings used for semantic search

VECTOR_SEARCH_TEXT_SPLITTER_CHUNK_OVERLAP=25 # Determines, for a given chunk of text, how many tokens must overlap with adjacent chunks.
VECTOR_SEARCH_SEARCH_N_RESULTS=4 # How many entries should the vector search return?
```
I have not changed the default values it seems. 

>> Do you have a sense what stage takes time (pulling results from the vector store vs. generating the response).

No idea. Sorry. 

>> I should note: there is a new version of WARC-GPT available that decouples search from completion.

I have noticed that my .env is differeing significantly with the example as given in the GitHub site of the project.
Could you plz guide how to Upgrade from this version? I found no clue in the Readme file. I have followed the instruction exactly as given in the Installation section of the Readme file.

Regards

**Comment by matteocargnelutti** [comment]
> I have noticed that my .env is differeing significantly with the example as given in the GitHub site of the project.
Could you plz guide how to Upgrade from this version? I found no clue in the Readme file. I have followed the instruction exactly as given in the Installation section of the Readme file.

For sure. There are a few brief notes on upgrading from 0.0.3 in the release notes of 1.0.0: https://github.com/harvard-lil/warc-gpt/releases/tag/0.1.0 

More generally: I would recommend re-installing from scratch if possible, for the reasons you mentioned. That said, you should be able to copy / paste your existing `chromadb` folder in that new install without having to run `flask ingest` again :)

Hope this helps.

**Comment by psmukhopadhyay** [comment]
@matteocargnelutti 

Thanks for the guidance.

I reinstalled the new version (0.1.0) from scratch and it re-ingested my 6 warc files. All went very smooth. Additionally I deleted the cache generated from the old version from this location (/home/<my home>/.cache/pypoetry/virtualenvs. The new directory created under under this cache directory, after the installation/ingestion processes,  is equal to the earlier one in size.

Started warc-gpt server but there two buttons are clickable - Settings (shows ollama/mistral:latest) and Inspect. **The other two buttons Stop and Ask are not clickable.**

![image](https://github.com/harvard-lil/warc-gpt/assets/19376596/2a438427-dfb0-4d82-8d8b-b247db77a9fd)

I restarted the laptop thinking it may be a cache issue but it is showing the same behaviour - **can't click the Ask button**. I can run Ollama mistral from command prompt and ask questions though. 

What am I missing?

Regards

**Comment by matteocargnelutti** [comment]
Hi @psmukhopadhyay -- The "Ask" button should become active as soon as the "question" field is no longer empty.

**Comment by psmukhopadhyay** [comment]
@matteocargnelutti 

In my case the default settings is always producing a disabled "Ask' button. However if I change combinations in settings like change of model (llama2 or mistral), Search enabled/disabled. History enabled/disabled etc the "Ask' button is activated. 

And then it is working nicely and promptly (there is no time delay like earlier version) but every time I need to shuffle options in settings to activate 'Ask' button. 

![image](https://github.com/harvard-lil/warc-gpt/assets/19376596/c96990bd-faf3-4c5a-87a7-e243b7407652)




Could you please guide me on the following?

1. How to enable Debug mode? 
2. Do you have any discussion forum/mailing list/Google group for the Warc-gpt?
3. How can we determine efficacy of different LLM models?

Regards

**Comment by psmukhopadhyay** [comment]
Could this line be the reason (in ui.py) for disabled 'Ask' button in my case in versions 0.1.1 and 0.1.0 (until I change from llama to mistral or mistral to llama) in the UI?

   **if model.startswith("ollama/mixtral"):**

Because when I change this to    if model.startswith("ollama/mistral"): - there is no issue with the disabled 'Ask' button.

Much relieved now...

**Comment by matteocargnelutti** [comment]
Good catch @psmukhopadhyay, thank you! 
I just pushed a PR with a fix for this problem. This fix will be part of WARC-GPT 0.1.2, which will hopefully be released later today.

**Comment by matteocargnelutti** [comment]
@psmukhopadhyay PS: All set :)

**Comment by psmukhopadhyay** [comment]
Great. I tested version 0.1.2, and it's performing well now - no disabled Ask button (although response time is still an issue for me). Now I understand your previous question: Do you have a sense of what stage takes time (pulling results from the vector store vs. generating the response)?

The search is almost instantaneous. It readily shows sources similar to the query. So, I believe pulling results from the vector store is working as expected. However, generation takes time (about 4 minutes on average per query to generate and complete with the corresponding references). Somewhere I read that large LLMs like Mistral have a warm-up time delay. Could someone suggest a brief but robust open LLM model to test whether it improves the time delay in generating the response for my case?

Regards
